//! Parity tests: validate Rust results against Python hmmlearn fixtures.
//!
//! Fixtures are generated by `tests/generate_fixtures.py` using hmmlearn.
//! These tests load the JSON fixtures and assert numerical parity
//! within defined tolerance tiers.

use hmm_rs::prelude::*;
use ndarray::{Array1, Array2, Array3};
use std::fs;

const SCORE_TOL: f64 = 1e-9;
const POSTERIOR_TOL: f64 = 1e-9;

fn load_fixture(name: &str) -> serde_json::Value {
    let path = format!("tests/fixtures/{}", name);
    let data = fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Fixture not found: {}. Run: python3 tests/generate_fixtures.py", path));
    serde_json::from_str(&data).unwrap()
}

fn json_to_array2(val: &serde_json::Value) -> Array2<f64> {
    let rows: Vec<Vec<f64>> = serde_json::from_value(val.clone()).unwrap();
    let nrows = rows.len();
    let ncols = rows[0].len();
    Array2::from_shape_fn((nrows, ncols), |(i, j)| rows[i][j])
}

fn json_to_array1(val: &serde_json::Value) -> Array1<f64> {
    let v: Vec<f64> = serde_json::from_value(val.clone()).unwrap();
    Array1::from_vec(v)
}

fn json_to_array3(val: &serde_json::Value) -> Array3<f64> {
    let data: Vec<Vec<Vec<f64>>> = serde_json::from_value(val.clone()).unwrap();
    let d0 = data.len();
    let d1 = data[0].len();
    let d2 = data[0][0].len();
    Array3::from_shape_fn((d0, d1, d2), |(i, j, k)| data[i][j][k])
}

// ==========================================================================
// CategoricalHMM parity
// ==========================================================================

#[test]
fn test_categorical_score_parity() {
    let fix = load_fixture("categorical.json");

    let mut model = CategoricalHmm::categorical(2);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.emissionprob_ = Some(json_to_array2(&fix["emissionprob"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "CategoricalHMM score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}

#[test]
fn test_categorical_decode_parity() {
    let fix = load_fixture("categorical.json");

    let mut model = CategoricalHmm::categorical(2);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.emissionprob_ = Some(json_to_array2(&fix["emissionprob"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let (rust_lp, rust_states) = model.decode(&x, &lengths, None).unwrap();
    let py_lp = fix["expected"]["decode_log_prob"].as_f64().unwrap();
    let py_states: Vec<usize> = fix["expected"]["decode_states"]
        .as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize)
        .collect();

    assert!(
        (rust_lp - py_lp).abs() < SCORE_TOL,
        "CategoricalHMM decode log_prob: Rust={} Python={}",
        rust_lp, py_lp
    );
    assert_eq!(
        rust_states.as_slice().unwrap(),
        &py_states[..],
        "CategoricalHMM decode states mismatch"
    );
}

#[test]
fn test_categorical_posteriors_parity() {
    let fix = load_fixture("categorical.json");

    let mut model = CategoricalHmm::categorical(2);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.emissionprob_ = Some(json_to_array2(&fix["emissionprob"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_post = model.predict_proba(&x, &lengths).unwrap();
    let py_post = json_to_array2(&fix["expected"]["posteriors"]);

    for i in 0..rust_post.nrows() {
        for j in 0..rust_post.ncols() {
            assert!(
                (rust_post[[i, j]] - py_post[[i, j]]).abs() < POSTERIOR_TOL,
                "CategoricalHMM posteriors[{},{}]: Rust={} Python={} diff={}",
                i, j, rust_post[[i, j]], py_post[[i, j]],
                (rust_post[[i, j]] - py_post[[i, j]]).abs()
            );
        }
    }
}

// ==========================================================================
// GaussianHMM (full covariance) parity
// ==========================================================================

#[test]
fn test_gaussian_full_score_parity() {
    let fix = load_fixture("gaussian_full.json");

    let mut model = GaussianHmm::gaussian(3, CovarianceType::Full);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.means_ = Some(json_to_array2(&fix["means"]));
    model.emission.covars_full_ = Some(json_to_array3(&fix["covars"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "GaussianHMM(full) score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}

#[test]
fn test_gaussian_full_decode_parity() {
    let fix = load_fixture("gaussian_full.json");

    let mut model = GaussianHmm::gaussian(3, CovarianceType::Full);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.means_ = Some(json_to_array2(&fix["means"]));
    model.emission.covars_full_ = Some(json_to_array3(&fix["covars"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let (rust_lp, rust_states) = model.decode(&x, &lengths, None).unwrap();
    let py_lp = fix["expected"]["decode_log_prob"].as_f64().unwrap();
    let py_states: Vec<usize> = fix["expected"]["decode_states"]
        .as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize)
        .collect();

    assert!(
        (rust_lp - py_lp).abs() < SCORE_TOL,
        "GaussianHMM(full) decode log_prob: Rust={} Python={}",
        rust_lp, py_lp
    );
    assert_eq!(
        rust_states.as_slice().unwrap(),
        &py_states[..],
        "GaussianHMM(full) decode states mismatch"
    );
}

// ==========================================================================
// GaussianHMM (diag covariance) parity
// ==========================================================================

#[test]
fn test_gaussian_diag_score_parity() {
    let fix = load_fixture("gaussian_diag.json");

    let nc = fix["n_components"].as_u64().unwrap() as usize;
    let nf = fix["n_features"].as_u64().unwrap() as usize;

    let mut model = GaussianHmm::gaussian(nc, CovarianceType::Diag);
    model.emission.n_features = Some(nf);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.means_ = Some(json_to_array2(&fix["means"]));
    // hmmlearn's covars_ property returns full matrices; extract diagonals
    let full_covars = json_to_array3(&fix["covars"]);
    let mut diag_covars = Array2::<f64>::zeros((nc, nf));
    for c in 0..nc {
        for f in 0..nf {
            diag_covars[[c, f]] = full_covars[[c, f, f]];
        }
    }
    model.emission.covars_diag_ = Some(diag_covars);
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "GaussianHMM(diag) score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}

// ==========================================================================
// PoissonHMM parity
// ==========================================================================

#[test]
fn test_poisson_score_parity() {
    let fix = load_fixture("poisson.json");

    let mut model = PoissonHmm::poisson(2);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.lambdas_ = Some(json_to_array2(&fix["lambdas"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "PoissonHMM score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}

#[test]
fn test_poisson_decode_parity() {
    let fix = load_fixture("poisson.json");

    let mut model = PoissonHmm::poisson(2);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.lambdas_ = Some(json_to_array2(&fix["lambdas"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let (rust_lp, rust_states) = model.decode(&x, &lengths, None).unwrap();
    let py_lp = fix["expected"]["decode_log_prob"].as_f64().unwrap();
    let py_states: Vec<usize> = fix["expected"]["decode_states"]
        .as_array().unwrap()
        .iter().map(|v| v.as_u64().unwrap() as usize)
        .collect();

    assert!(
        (rust_lp - py_lp).abs() < SCORE_TOL,
        "PoissonHMM decode log_prob: Rust={} Python={}",
        rust_lp, py_lp
    );
    assert_eq!(
        rust_states.as_slice().unwrap(),
        &py_states[..],
        "PoissonHMM decode states mismatch"
    );
}

// ==========================================================================
// GaussianHMM (spherical covariance) parity
// ==========================================================================

#[test]
fn test_gaussian_spherical_score_parity() {
    let fix = load_fixture("gaussian_spherical.json");
    let nc = fix["n_components"].as_u64().unwrap() as usize;
    let nf = fix["n_features"].as_u64().unwrap() as usize;

    let mut model = GaussianHmm::gaussian(nc, CovarianceType::Spherical);
    model.emission.n_features = Some(nf);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.means_ = Some(json_to_array2(&fix["means"]));
    // hmmlearn covars_ returns full (nc, nf, nf) matrices; extract scalar variance per component
    let full_covars = json_to_array3(&fix["covars"]);
    let mut sph = Array1::<f64>::zeros(nc);
    for c in 0..nc {
        // Average diagonal (spherical = same variance for all features)
        let mut sum = 0.0;
        for f in 0..nf {
            sum += full_covars[[c, f, f]];
        }
        sph[c] = sum / nf as f64;
    }
    model.emission.covars_spherical_ = Some(sph);
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "GaussianHMM(spherical) score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}

// ==========================================================================
// GaussianHMM (tied covariance) parity
// ==========================================================================

#[test]
fn test_gaussian_tied_score_parity() {
    let fix = load_fixture("gaussian_tied.json");
    let nc = fix["n_components"].as_u64().unwrap() as usize;
    let nf = fix["n_features"].as_u64().unwrap() as usize;

    let mut model = GaussianHmm::gaussian(nc, CovarianceType::Tied);
    model.emission.n_features = Some(nf);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.means_ = Some(json_to_array2(&fix["means"]));
    // hmmlearn covars_ returns (nc, nf, nf) for tied; all identical — take first
    let full_covars = json_to_array3(&fix["covars"]);
    model.emission.covars_tied_ = Some(full_covars.index_axis(ndarray::Axis(0), 0).to_owned());
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "GaussianHMM(tied) score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}

// ==========================================================================
// MultinomialHMM parity
// ==========================================================================

#[test]
fn test_multinomial_score_parity() {
    let fix = load_fixture("multinomial.json");
    let nc = fix["n_components"].as_u64().unwrap() as usize;

    let mut model = MultinomialHmm::multinomial(nc);
    model.emission.n_features = Some(fix["n_features"].as_u64().unwrap() as usize);
    model.emission.n_trials = Some(5);
    model.startprob_ = json_to_array1(&fix["startprob"]);
    model.transmat_ = json_to_array2(&fix["transmat"]);
    model.emission.emissionprob_ = Some(json_to_array2(&fix["emissionprob"]));
    model.fitted = true;

    let x = json_to_array2(&fix["X"]);
    let lengths = [x.nrows()];

    let rust_score = model.score(&x, &lengths).unwrap();
    let py_score = fix["expected"]["score"].as_f64().unwrap();

    assert!(
        (rust_score - py_score).abs() < SCORE_TOL,
        "MultinomialHMM score: Rust={} Python={} diff={}",
        rust_score, py_score, (rust_score - py_score).abs()
    );
}
